config/routes.rb
Rails.application.routes.draw do
  root "tops#index"
  resources :users, only: [:new, :create]
  resources :user_sessions, only: [:new, :create, :destroy]
  delete 'logout', to: 'user_sessions#destroy', as: :logout
  get 'logout', to: 'user_sessions#destroy'
  get "up" => "rails/health#show", as: :rails_health_check
  get 'login', to: 'user_sessions#new', as: :login

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

    validates :username, presence: true, uniqueness: true
    validates :email, presence: true
    validates :password, presence: true
    validates :password, confirmation: true
    has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :require_login
    def require_login
      unless logged_in?
        redirect_to new_user_session_path, alert: "ログインが必要です"
      end
    end

    private

    def not_authenticated
      redirect_to login_path, danger: "ログインしてください"
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @post, notice: 'コメントが追加されました。'
    else
      redirect_to @post, alert: 'コメントの追加に失敗しました。'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @comment.post, notice: 'コメントが削除されました。'
  end

  private

    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to posts_path, alert: "指定されたポストが見つかりません。"
  end
  

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: '投稿が作成されました。'
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end
  

  def update
    if @post.update(post_params)
      redirect_to @post, notice: '投稿が更新されました。'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: '投稿が削除されました。'
  end

  private
  def set_post
    @post = Post.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to posts_url, alert: "指定されたポストが見つかりません。"
  end

    def post_params
      params.require(:post).permit(:title, :body, :url)
    end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
    skip_before_action :require_login
    def index; end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
    skip_before_action :require_login, only: %i[create new]

    def new
    end

    def create
      @user = login(params[:email], params[:password])

      if @user
        redirect_back_or_to(root_path, notice: 'ログインに成功しました')
      else
        flash.now[:alert] = 'ログインに失敗しました'
        render :new
      end
    end

    def destroy
      logout
      redirect_to(login_path, notice: 'ログアウトしました')
    end    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :require_login, only: %i[create new]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            flash[:notice] = "User created successfully"
            redirect_to root_path
        else
            render 'new'
        end
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBridge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome-animation/0.0.10/font-awesome-animation.css" type="text/css" media="all" />
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<section class="bg-size-cover bg-position-bottom-center bg-repeat-0 py-5" style="background-image: url(assets/img/contacts/bg.svg);">
    <div class="container pt-5 pb-lg-4 pb-xl-5">
        <div class="row pt-md-2 pt-lg-5 pb-2 pb-md-4">
            <div class="col-xxl-4 col-xl-5 col-lg-6 pt-3 mt-3">
                <h1 class="h3 mb-2">投稿を編集しますか?</h1>
                <h2 class="display-1 text-gradient-primary pb-sm-2 pb-md-3 mb-3">Edit & Update!</h2>
                <div class="nav d-block lead pt-lg-5">
                </div>
            </div>
            <div class="col-lg-6 offset-xl-1 offset-xxl-2 pt-3 pt-md-4 pt-lg-3 mt-3">
                <%= form_with model: @post, local: true, class: "needs-validation" do |f| %>
                    <div class="row g-4">
                        <div class="col-sm-6">
                            <%= f.label :title, class: "form-label fs-base" %>
                            <%= f.text_field :title, class: "form-control form-control-lg" %>
                        </div>
                        <div class="col-12 pb-2">
                            <%= f.label :body, class: "form-label fs-base" %>
                            <%= f.text_area :body, class: "form-control form-control-lg", rows: 3 %>
                        </div>
                        <div class="col-sm-6">
                            <%= f.label :url, class: "form-label fs-base" %>
                            <%= f.text_field :url, class: "form-control form-control-lg" %>
                        </div>
                        <div class="col-12 pb-2">
                        <div class="col-12">
                            <%= f.submit "投稿を更新", class: "btn btn-lg btn-primary w-100 w-sm-auto" %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</section>

app/views/posts/index.html.erb
<!-- Page content -->
<section class="container pt-5">
  <div class="row">

    <!-- Account collections -->
    <div class="col-md-8 offset-lg-1 pb-5 mb-lg-2 pt-md-5 mt-n3 mt-md-0">
      <div class="ps-md-3 ps-lg-0 mt-md-2 pt-md-4 pb-md-2">
        <div class="d-sm-flex align-items-center justify-content-between pt-xl-1 mb-3 pb-3">
          <h1 class="h2 mb-sm-0">みんなの開発アプリ</h1>
        </div>

        <% @posts.each do |post| %>
          <!-- Item -->
          <div class="card border-0 shadow-sm overflow-hidden mb-4">
            <div class="row g-0">
              <div class="col-sm-8">
                <div class="card-body">
                  <div class="fs-sm text-muted mb-1"><%= post.created_at.strftime('%b %d, %Y') %></div>
                  <h2 class="h4 pb-1 mb-2">
                    <%= link_to post.title, post_path(post) %>
                  </h2>
                  <div class="d-flex">
                    <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-outline-primary px-3 px-lg-4 me-3' %>
                    <!-- Additional buttons like Deactivate or Delete can go here -->
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/posts/new.html.erb
<section class="bg-size-cover bg-position-bottom-center bg-repeat-0 py-5" style="background-image: url(assets/img/contacts/bg.svg);">
    <div class="container pt-5 pb-lg-4 pb-xl-5">
        <div class="row pt-md-2 pt-lg-5 pb-2 pb-md-4">
        <div class="col-xxl-4 col-xl-5 col-lg-6 pt-3 mt-3">
            <h1 class="h3 mb-2">アイデアを思いつきましたか?</h1>
            <h2 class="display-1 text-gradient-primary pb-sm-2 pb-md-3 mb-3">Let's Share!</h2>
            <div class="nav d-block lead pt-lg-5">
            </div>
        </div>
        <div class="col-lg-6 offset-xl-1 offset-xxl-2 pt-3 pt-md-4 pt-lg-3 mt-3">
            <%= form_with model:@post, local: true, class:"needs-validation" do |f| %>
                <div class="row g-4">
                    <div class="col-sm-6">
                        <%= f.label :title, class:"form-label fs-base" %>
                        <%= f.text_field :title, class: "form-control form-control-lg" %>
                    </div>
                    <div class="col-12 pb-2">
                        <%= f.label :body, class:"form-label fs-base" %>
                        <%= f.text_field :body, class: "form-control form-control-lg" %>
                    </div>
                    <div class="col-sm-6">
                        <%= f.label :url, class:"form-label fs-base" %>
                        <%= f.text_field :url, class: "form-control form-control-lg" %>
                    </div>
                    <div class="col-12 pb-2">
                    <div class="col-12">
                    <%= f.submit "新規投稿", class: "btn btn-lg btn-primary w-100 w-sm-auto" %>
                    </div>
                </div>
            <%end%>
            </form>
        </div>
        </div>
    </div>
</section>

app/views/posts/show.html.erb
<div style="background-size: cover; background-position: center;">
  <section class="container py-5 mt-5 mt-md-4 mb-md-3 mb-lg-4 mb-xl-5">
    <div class="row align-items-center align-items-lg-stretch mb-2 mb-sm-3">
      <!-- Parallax gfx -->
      <div class="col-xl-7 col-md-6 d-flex justify-content-center justify-content-md-end overflow-hidden order-md-2 mt-n5 mt-sm-n4 mt-md-0">
        <div class="position-relative mt-5" style="max-width: 660px;">
          <div class="parallax zindex-2">
            <div class="parallax-layer zindex-2 mb-n3 card card-hover shadow p-3 mb-1" data-depth="0.1">
            </div>
          </div>
        </div>
      </div>

      <!-- Text -->
      <div class="col-xl-5 col-md-6 d-flex flex-column order-md-1">
        <div class="text-center text-md-start pt-4 pt-sm-5 pt-xl-0 mt-2 mt-sm-0 mt-lg-auto">
          <h1 class="display-3 mb-4"><%= @post.title %> 、<br>を考えています</h1>
          <h2 href="#" class="fw-semibold"><%= @post.body %></h2>
          <a href="#" class="fw-semibold"><%= @post.url %></a>
          <span class="d-block mb-3"><%= @post.created_at.strftime('%Y年%m月%d日 %H:%M') %></span>
          <h6>Share & いいね！</h6>
          <div class="d-flex align-items-center">
          <%= link_to '編集', edit_post_path(@post) %> |
          <%= link_to '一覧に戻る', posts_path %>.
          </div>
        </div>
      </div>
    </div>
    <div style="height: 50px;"></div>
          <!-- Page content -->
      <section class="container pt-5">
        <div class="row">

          <!-- Account messages -->
          <div class="col-md-8 col-lg-9 pb-5 mb-lg-2 mb-lg-4 pt-md-5 mt-n3 mt-md-0">
            <div class="ps-md-3 mt-md-2 pt-md-4 pb-md-2">
              <div class="row g-0 border rounded-3 shadow-sm position-relative overflow-hidden">

                    <!-- Messages -->
                    <div class="card-body swiper scrollbar-hover overflow-hidden w-100 pb-0" data-swiper-options='{
                      "direction": "vertical",
                      "slidesPerView": "auto",
                      "freeMode": true,
                      "scrollbar": {
                        "el": ".swiper-scrollbar"
                      },
                      "mousewheel": true
                    }'>
                      <div class="swiper-wrapper">
                        <div class="swiper-slide h-auto">
                          <div class="fs-sm text-muted text-center mb-3"></div>

                          <!-- User message -->
                          <div class="d-flex align-items-start mb-3">
                            <img src="assets/img/avatar/20.jpg" class="rounded-circle" width="40" alt="Albert Flores">
                            <div class="ps-2 ms-1" style="max-width: 348px;">
                              <div class="bg-secondary p-3 mb-1" style="border-top-right-radius: .5rem; border-bottom-right-radius: .5rem; border-bottom-left-radius: .5rem;">いいね！</div>
                              <div class="fs-sm text-muted">09:04 am</div>
                            </div>
                          </div>

                          <!-- Own message -->
                          <div class="d-flex align-items-start justify-content-end mb-3">
                            <div class="pe-2 me-1" style="max-width: 348px;">
                              <div class="bg-primary text-light p-3 mb-1" style="border-top-left-radius: .5rem; border-bottom-right-radius: .5rem; border-bottom-left-radius: .5rem;">ナイスアイデア</div>
                              <div class="d-flex justify-content-end align-items-center fs-sm text-muted">
                                10:36 am
                                <i class="bx bx-check-double fs-xl text-primary ms-2"></i>
                              </div>
                            </div>
                            <img src="assets/img/avatar/29.jpg" class="rounded-circle" width="40" alt="Albert Flores">
                          </div>

                          <!-- User message -->
                          <div class="d-flex align-items-start mb-3">
                            <img src="assets/img/avatar/20.jpg" class="rounded-circle" width="40" alt="Albert Flores">
                            <div class="ps-2 ms-1" style="max-width: 348px;">
                              <div class="bg-secondary p-3 mb-1" style="border-top-right-radius: .5rem; border-bottom-right-radius: .5rem; border-bottom-left-radius: .5rem;">ありがとう！</div>
                              <div class="fs-sm text-muted">14:48 pm</div>
                            </div>
                          </div>

                          <!-- Own message -->
                          <div class="d-flex align-items-start justify-content-end mb-3">
                            <div class="pe-2 me-1" style="max-width: 348px;">
                              <div class="bg-primary text-light p-3 mb-1" style="border-top-left-radius: .5rem; border-bottom-right-radius: .5rem; border-bottom-left-radius: .5rem;">他にはどんなものがあるかな？</div>
                              <div class="bg-primary text-light p-3 mb-1" style="border-top-left-radius: .5rem; border-bottom-right-radius: .5rem; border-bottom-left-radius: .5rem;">参考になるものがあればぜひ</div>
                              <div class="d-flex justify-content-end align-items-center fs-sm text-muted">
                                16:29 pm
                                <i class="bx bx-check fs-xl text-primary ms-2"></i>
                              </div>
                            </div>
                            <img src="assets/img/avatar/29.jpg" class="rounded-circle" width="40" alt="Albert Flores">
                          </div>

                          <div class="fs-sm text-muted text-center mb-3">November 28, 2023</div>

                          <!-- User message -->
                          <div class="d-flex align-items-start mb-3">
                            <img src="assets/img/avatar/20.jpg" class="rounded-circle" width="40" alt="Albert Flores">
                            <div class="ps-2 ms-1" style="max-width: 348px;">
                              <div class="bg-secondary p-3 mb-1" style="border-top-right-radius: .5rem; border-bottom-right-radius: .5rem; border-bottom-left-radius: .5rem;">りょーかい 😊</div>
                              <div class="fs-sm text-muted">17:33 pm</div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="swiper-scrollbar end-0"></div>
                    </div>

                    <!-- Footer (Send message form) -->
                    <div class="card-footer d-sm-flex w-100 border-0 pt-3 pb-3 px-4">
                      <div class="position-relative w-100 me-2 mb-3 mb-sm-0">
                        <input type="text" class="form-control form-control-lg" style="padding-right: 85px;">
                        <div class="position-absolute top-50 end-0 translate-middle-y d-flex zindex-3 me-2">
                          <button type="button" class="btn btn-icon btn-sm btn-link nav-link bg-faded-primary-hover me-1" aria-label="Attachment">
                            <i class="bx bx-paperclip fs-4"></i>
                          </button>
                          <button type="button" class="btn btn-icon btn-sm btn-link nav-link bg-faded-primary-hover" aria-label="Emoji">
                            <i class="bx bx-smile fs-4"></i>
                          </button>
                        </div>
                      </div>
                      <button type="button" class="btn btn-primary btn-icon btn-lg d-none d-sm-inline-flex ms-1" aria-label="Send">
                        <i class="bx bx-send"></i>
                      </button>
                      <button type="button" class="btn btn-primary btn-lg w-100 d-sm-none">
                        <i class="bx bx-send fs-xl me-2"></i>
                        Send
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </main>
  </section>
</div>

app/views/shared/_footer.html.erb
<footer class="footer bg-dark border-top border-light pt-5 pb-4 pb-lg-5 mt-auto" data-bs-theme="white">
  <div class="container pt-xl-4">
    <div class="row pb-5">
      <div class="col-lg-4 col-md-6">
        <div class="navbar-brand text-dark p-0 me-0 mb-3 mb-lg-4">
          RailsBridge
        </div>
      </div>
      <div class="col-xl-6 col-lg-7 col-md-5 offset-xl-2 offset-md-1 pt-4 pt-md-1 pt-lg-0">
        <div id="footer-links" class="row">
          <div class="col-xl-4 col-lg-3">
            <h6 class="mb-2">
              <a href="#social-links" class="d-block text-dark dropdown-toggle d-lg-none py-2" data-bs-toggle="collapse">Socials</a>
            </h6>
          </div>
        </div>
      </div>
    </div>
    <p class="nav d-block fs-xs text-center ">
      <span class="text-light opacity-50">&copy; RailsBridge forever </span>
    </p>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="header navbar navbar-expand-lg bg-light navbar-sticky">
  <div class="container px-3">
    <%= link_to "RailsBridge", root_path, class: "navbar-brand pe-3" %>
    <button type="button" class="navbar-toggler" data-bs-toggle="offcanvas" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div id="navbarNav" class="offcanvas offcanvas-end">
      <div class="offcanvas-header border-bottom">
        <h5 class="offcanvas-title">Menu</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <% if logged_in? %>
          <!-- 追加したPostsリンク -->
          <li class="nav-item">
            <%= link_to "New Post", new_post_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Posts", posts_path, class: "nav-link" %>
          </li>
            <% else %>
            <% end %>
          <!-- Account Dropdown -->
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
              Account
            </a>
            <ul class="dropdown-menu">
              <% if logged_in? %>
                  <%= button_to 'ログアウト', logout_path, method: :delete, class: "dropdown-item" %>
              <% else %>
                <%= link_to "ログイン", new_user_session_path, class: "dropdown-item" %>
                <%= link_to "会員登録", new_user_path, class: "dropdown-item" %>
              <% end %>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/tops/index.html.erb
    <main class="page-wrapper">


      <!-- Navbar -->
      <!-- Remove "navbar-sticky" class to make navigation bar scrollable with the page -->


      <!-- Hero image -->
     <div class="jarallax d-none d-md-block" data-jarallax data-speed="0.35">
      <span class="position-absolute top-0 start-0 w-100 h-100 bg-gradient-primary-translucent"></span>
      <div class="bg-cover" style="background-image: url(<%= asset_path 'railsbridge.webp' %>); background-repeat: no-repeat; background-size: contain; background-position: center;">
      <div class="d-none d-xxl-block" style="height: 700px;"></div>
      <div class="d-none d-md-block d-xxl-none" style="height: 850px;"></div>
      </div>
    </div>


      <!-- Breadcrumb -->
      <nav class="container py-4 mb-2 my-lg-3" aria-label="breadcrumb">
        <ol class="breadcrumb mb-0">
          <li class="breadcrumb-item">
            <a href="index.html"><i class="bx bx-home-alt fs-lg me-1"></i>Home</a>
          </li>
          <li class="breadcrumb-item active" aria-current="page">About v.2</li>
        </ol>
      </nav>


      <!-- About company -->
      <section class="container pb-5 mb-md-2 mb-lg-4">
        <h1 class="border-bottom pb-4">Rails bridgeとは</h1>
        <div class="row pt-2 pt-md-3">
          <div class="col-md-6">
            <p class="fs-lg pe-lg-4 mb-1 mb-lg-4">Railsに特化した個人開発で悩み解決、レビューしてもらえるサービスです。</p>
          </div>
        </div>
      </section>


      <!-- Stats -->
      <section class="container pb-5 mb-2 mb-md-4 mb-lg-5">
        <div class="bg-secondary rounded-3 py-5 px-3 px-md-0">
          <div class="row justify-content-center mb-2 py-md-2 py-lg-4">
            <div class="col-lg-10 col-md-11">
              <h2 class="pb-3">何ができるの？
              </h2>
              <div class="row row-cols-1 g-4">

                <!-- Item -->
                <div class="col">
                  <div class="card h-100 border-0 shadow-sm p-md-2 p-lg-4">
                    <div class="card-body d-flex align-items-center">
                      <div class="bg-primary shadow-primary rounded-3 flex-shrink-0 p-3">
                      <div class="ps-4 ms-lg-3">
                        <h3 class="display-5 mb-1">自身の作ったアプリをレビューしてもらえる</h3>
                        <p class="mb-0"><span class="fw-semibold">New Clients</span> per Month</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

          <!-- Pagination (bullets) -->
          <div class="swiper-pagination position-relative pt-3 mt-3"></div>
        </div>
      </section>
    </main>

app/views/user_sessions/new.html.erb
<div class="container d-flex flex-wrap justify-content-center justify-content-xl-start h-100 pt-5">
    <div class="w-100 align-self-end pt-1 pt-md-4 pb-4" style="max-width: 526px;">
    <h1 class="text-center text-xl-start">Welcome Back</h1>
    <p class="text-center text-xl-start pb-3 mb-3">Don’t have an account yet? <a href="account-signup.html">Register here.</a></p>
    <%= form_with url: user_sessions_path, local: true, html: {class:"needs-validation"} do |f| %>
        <div class="position-relative mb-4">
            <%= f.label :email, class: "form-label fs-base" %>
            <%= f.email_field :email, class: "form-control form-control-lg" %>
        </div>
        <div class="position-relative mb-4">
            <%= f.label :password, class: "form-label fs-base" %>
            <%= f.password_field :password, class: "form-control form-control-lg" %>
        </div>
        <div class="mb-4">
        <%= f.submit "ログイン", class:"btn btn-primary shadow-primary btn-lg w-100"%>
    <%end%>
    <div class="w-100 align-self-end">
    <p class="nav d-block fs-xs text-center text-xl-start pb-2 mb-0">
        &copy; All rights reserved. Made by
    </p>
    </div>
</div>

app/views/users/new.html.erb
<body class="d-flex flex-column min-vh-100">

<main class="flex-grow-1">
  <!-- Page content -->
  <section class="pt-5 pb-4">
    <!-- Sign in form -->
    <div class="container d-flex flex-wrap justify-content-center justify-content-xl-start pt-5">
      <div class="w-100 pt-1 pt-md-4 pb-4" style="max-width: 526px;">
        <h1 class="text-center text-xl-start">Welcome Back</h1>
      <p class="text-center text-xl-start pb-3 mb-3">Don’t have an account yet? <a href="account-signup.html">Register here.</a></p>
      <%= form_with model: @user, local: true, html: {class:"needs-validation"} do |f| %>
        <div class="position-relative mb-4">
          <%= f.label :username, class: "form-label fs-base" %>
          <%= f.text_field :username, class: "form-control form-control-lg" %>
        </div>
        <div class="position-relative mb-4">
          <%= f.label :email, class: "form-label fs-base" %>
          <%= f.email_field :email, class: "form-control form-control-lg" %>
        </div>
        <div class="position-relative mb-4">
          <%= f.label :password, class: "form-label fs-base" %>
          <%= f.password_field :password, class: "form-control form-control-lg" %>
        </div>
        <div class="position-relative mb-4">
          <%= f.label :password_confirmation, class: "form-label fs-base" %>
          <%= f.password_field :password_confirmation, class: "form-control form-control-lg" %>
        </div>
        <div class="mb-4">
          <%= f.submit "会員登録", class:"btn btn-primary shadow-primary btn-lg w-100" %>
        </div>
      <% end %>
      <div class="w-100 align-self-end">
        <p class="nav d-block fs-xs text-center text-xl-start pb-2 mb-0">
          &copy; All rights reserved. Made by
          <a class="nav-link d-inline-block p-0" href="https://createx.studio/" target="_blank" rel="noopener">Createx Studio</a>
        </p>
      </div>
    </div>
  </div>
  <!-- Background -->
  <div class="position-absolute top-0 end-0 w-50 h-100 bg-position-center bg-repeat-0 bg-size-cover d-none d-xl-block" style="background-image: url(assets/img/account/signin-bg.jpg);"></div>
</section>
</main>